---
hostname: "sw2"
prod_ip_addr: "192.168.66.12"
# Имя и порты моста коммутатора
bridge_name: "bridge1"
# Порты ISL для MC-LAG
peerlink_name: "peerlink"
peerlink_ports: "swp2-3"
peerlink_mac_address: "44:38:39:FF:40:94"
peerlink_ip_addr: "169.254.0.2"
peerlink_ip_cidr: "30"
peerlink_ip_opposite: "169.254.0.1"
peerlink_backup_ip: "192.168.66.11"
router_bond_name: "r1"
router_port: "swp1"
router_clagid: "1"
auth1_bond_name: "auth1"
auth1_port: "swp4"
auth1_clagid: "2"
auth2_bond_name: "auth2"
auth2_port: "swp5"
auth2_clagid: "3"
mon_bond_name: "mon"
mon_port: "swp6"
mon_clagid: "4"
pcm1_bond_name: "pcm1"
pcm1_port: "swp7"
pcm1_clagid: "5"
pcm2_bond_name: "pcm2"
pcm2_port: "swp8"
pcm2_clagid: "6"
pcm3_bond_name: "pcm3"
pcm3_port: "swp9"
pcm3_clagid: "7"
...